### ISSUE TITLE
Translate the new text

### ISSUE THREAD

**Issue by ghost** [Young-Lord/fight-for-the-open-web#10]
#8 added new text, but it's only translated in English. Maybe the new text should be translated to the other languages.

**Comment by Young-Lord** [comment]
@GreyXor @pacifi5t @cardpuncher 
Is it OK for you to do this?

**Comment by cardpuncher** [comment]
On 6.08.2023 12:13, LY wrote:
> @GreyXor <https://github.com/GreyXor> @pacifi5t 
> <https://github.com/pacifi5t> @cardpuncher <https://github.com/cardpuncher>
> Is it OK for you to do this?

Sure, PR just sent.

**Comment by pacifi5t** [comment]
> @GreyXor @pacifi5t @cardpuncher Is it OK for you to do this?

Yeah, no problem
