### ISSUE TITLE
FSF made clear oppsite statements on WEI which should be added to readme

### ISSUE THREAD

**Issue by ZeroAurora** [Young-Lord/fight-for-the-open-web#11]
https://www.fsf.org/blogs/community/web-environment-integrity-is-an-all-out-attack-on-the-free-internet

Will open a PR

**Comment by Young-Lord** [comment]
以及，请问您愿意把简体中文的readme与message翻译一下吗？

**Comment by ZeroAurora** [comment]
有空就翻
