### ISSUE TITLE
MAINTAINER WANTED

### ISSUE THREAD

**Issue by Young-Lord** [Young-Lord/fight-for-the-open-web#21]
For schoolwork reason, I may not be able to process issues & PRs timely.
Anyone interested in this project and proven not *evil* is welcome.

#7 should be solved before this happens.

**Comment by ghost** [comment]
I am happy to help maintain the project. School is still out for me and I have more free time because I do school online anyways.

**Comment by Young-Lord** [comment]
> I am happy to help maintain the project. School is still out for me and I have more free time because I do school online anyways.

if you're not certain about any pr, wait others review before merge. DO test every feature-related commits before merge.
I may be able to review every Sunday.

**Comment by ghost** [comment]
Got it, thanks

I'm in pacific time in the US, what times on Sunday (or other days I guess) would you usually be available in pacific time?
