### ISSUE TITLE
additional words regarding WEIs.

### ISSUE THREAD

**Issue by lottery248** [Young-Lord/fight-for-the-open-web#24]
so web environment integrity in its simplest form is the "website DRM". 

it has been for a while that certain copyright owners are protecting their works from being pirated, those people would definitely want all these protections because it would help them fend off those. these protections had only led to more piracy due to the uncertainties on the legal side.

on the other hand, i have been a livestreamer on YouTube for more than 5 years, and recently, YouTube made certain chat moderation tools because there was a period of spambots floating everywhere, and during a period, there were bots trying to get channels banned having pornographic profile picture when the livestreamer has a chatbox in his own live tape. one of these tool is "subscriber-only mode" which obviously only allows users who has subscribed to that channel for a certain period before he can post anything during live. however, what i found is that they didn't solve the very problem at all.

more websites, especially the big ones hosting NSFWs, even if they are not required by law, are at least requiring people to be logged in or even to verify their identity just to prove their legitimacy. indeed, the underage should be gated, but we aren't doing this in real life but online that will end up certain digital traces, and no one would actually care about the RTA label (a preexisting solution) that is used to filter out the websites should be shown to them while then not annoying the legal users; without considering the potential treachery on the part of the site owners (imagine what would happen if the website got breached).

there will be a mass network attack so that websites race to join their WEI like YouTube wanted channels to protect themselves that way, and website owners should rather find another solution to tackle this attack, because joining them only ruins them completely.

website operators should consider backing up all the data for the case of attacks or sudden takedowns.

@jbruchon made this video explaining how nefarious this kind of movement is: https://www.youtube.com/watch?v=tdpNsd5GKX8

**Comment by ghost** [comment]
> it has been for a while that certain copyright owners are protecting their works from being pirated, those people would definitely want all these protections because it would help them fend off those. these protections had only led to more piracy due to the uncertainties on the legal side.

This is kind of true, but also, DRM has a tendency to be used just for restricting people in general for profit, like restricting what computers you can use to listen to audio files, what components you can install on a phone you bought, etc. Laws against DRM circumvention apply even if you aren't circumventing it to infringe copyright. Characterizing DRM as intellectual "property" or saying that it protects copyright is only half the story.

> indeed, the underage should be gated

https://www.eff.org/deeplinks/2023/03/age-verification-mandates-would-undermine-anonymity-online

I'm 15 and I've seen a lot of things online that I wish I didn't, but revoking anonymity from websites isn't the right way to do that

I care about the problem, but I don't agree with that solution

**Comment by jbruchon** [comment]
Age-gating is always evil because it relies on age verification to function which ultimately relies on government (or monopolistic corporation that is functionally similar to government) authority to function. Do not punish adults because children exist.

**Comment by lottery248** [comment]
> Laws against DRM circumvention apply even if you aren't circumventing it to infringe copyright. Characterizing DRM as intellectual "property" or saying that it protects copyright is only half the story.

this is why open source has been skyrocketing in popularity lately. as such, protecting copyright as if they are physical property deserves none.

> I'm 15 and I've seen a lot of things online that I wish I didn't, but revoking anonymity from websites isn't the right way to do that

> Age-gating is always evil because it relies on age verification to function which ultimately relies on government (or monopolistic corporation that is functionally similar to government) authority to function. Do not punish adults because children exist.

i agree, but i never said that age verification is anywhere a good thing. RTA label as mentioned, is a preexisting opt-in age-gating solution for parents (all they have to do is by properly configuring the filter within their devices to block access from those website) while keeping complete anonymity for those otherwise. this kind of solution is barely mentioned in elsewhere when it should.

**Comment by ghost** [comment]
> i agree, but i never said that age verification is anywhere a good thing. RTA label as mentioned, is a preexisting opt-in age-gating solution for parents (all they have to do is by properly configuring the filter within their devices to block access from those website) while keeping complete anonymity for those otherwise. this kind of solution is barely mentioned in elsewhere when it should.

Ah I see. I must've misread. That probably would work.
