### ISSUE TITLE
Needs support of detection same stuff from Apple

### ISSUE THREAD

**Issue by slavanap** [Young-Lord/fight-for-the-open-web#26]
https://blog.cloudflare.com/eliminating-captchas-on-iphones-and-macs-using-new-standard/

**Comment by ghost** [comment]
This doesn't seem as bad as WEI but I could be wrong, what does it do?

**Comment by slavanap** [comment]
Same thing: browser authenticity confirmation via Apple's attestation.

**Comment by Young-Lord** [comment]
> Same thing: browser authenticity confirmation via Apple's attestation.

Seems like this is processed by browser itself, but not JavaScript API. To detect it, the only way is to intercept HTTP requests (on client side) / send attestation request (on server side).
And iOS users do not have choice other than WebKit based browsers, so I don't think this repo is an effective way to protest against it.
Last, as it's currently only a iOS-only API and only few websites (AFAIK less than 10) is using it (as an optional alternative), so I don't think it's such a threat currently.
I'll monitor its status and take action, but not now.
btw, if you have simple ways to detect the PAT, feel free to reply / open a pr.
