### ISSUE TITLE
Victory?

### ISSUE THREAD

**Issue by pacifi5t** [Young-Lord/fight-for-the-open-web#31]
Google decided not to implement WEI in browsers. But they're doing basically the same thing for WebViews.

Source: https://9to5google.com/2023/11/02/google-chrome-web-integrity-api/

**Comment by Young-Lord** [comment]
It's good to see that this project reached its goal.
I don't think there's much we can do about this Android Webview only Integrity, the Android ecosystem has always been controlled by Google, and the Play Integrity API / Widevine DRM confrontation has always been a cat-and-mouse game, and I don't have any ability to even formally confront it. I don't have any ability to fight against it even formally. Therefore, this project has come to an end.
I will update the README, remove all the code from the js file and replace it with a line reminding to remove the `console.log` of this js file. This project will not be Archive, but there will not be any updates either.
There is a saying in China, `Chinese temperament is always like to reconcile and compromise. For example, if you say that this room is too dark and you need to open a window here, people will definitely not allow it. But if you advocate removing the roof, they will come to an accommodation and be willing to open a window." In a similar vein, I don't think this new proposal is going to set off massive opposition, and therefore as stated above, have no incentive to engage in any confrontation.


Translated by DeepL

很欣慰看到这个项目达到了它的目标。关于这个Android Webview only Integrity，我并不认为我们能做什么。Android生态系统一直是受谷歌控制的，对于Play Integrity API / Widevine DRM的对抗也一直是处于猫鼠游戏的状态，我没有任何能力哪怕是仅仅从形式上去对抗它。因此，这个项目算是走到尽头了
我将更新README、将js文件中的代码全部删除并替换为一行提醒移除此js文件的`console.log`。此项目不会Archive，但也不会有任何更新。
中国有句话，“中国人的性情是总喜欢调和，折中的。譬如你说，这屋子太暗，须在这里开一个窗，大家一定不允许的。但如果你主张拆掉屋顶，他们就会来调和，愿意开窗了。”与之相似的，我也不认为这个新的proposal会掀起大规模的反对，也因此就像上面所述，并无动机进行任何对抗。

**Comment by pacifi5t** [comment]
Yeah, I agree. I believe I should nevertheless thank everyone for their time and effort.

**Comment by jstrydom46-sketch** [comment]
#24
